title: Timiu's website
url: ''
baseurl: ''
google_analytics_key: null
google_maps_javascript_api_key: AIzaSyBYY5sb2_cmip-_t122_IH0mxh7l3IERMg
disqus_shortname: null
logo: /siteicon.png
description: A personal website of Timiu
author:
  name: Liudongnan Yang
  email: Liudongnan.yang@foxmail.com
  twitter: null
social:
  name: Timiu
  links:
    - 'https://github.com/yldn'
timezone: Etc/UTC
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
excloudcannonude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
collections:
  staff_members:
    _hide_content: true
    _icon: account_circle
paginate: 10
paginate_path: '/blog/:num/'
jekyll-archives:
  enabled:
    - categories
defaults:
  - scope:
      path: ''
      type: staff_members
    values:
      _options:
        image_path:
          width: 440
          height: 440
          uploads_dir: /images/staff_members
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      _options:
        image:
          width: 2000
          height: 1322
          resize_style: cover
          uploads_dir: /images/post_uploads
        content:
          width: 1500
          height: 2000
          uploads_dir: /images/post_uploads
  - scope:
      path: contact-success.html
    values:
      layout: page
  - scope:
      path: ''
      type: pages
    values:
      image:
        width: 2000
        height: 1322
        resize_style: cover
      bottom_image:
        width: 2000
        height: 1322
        resize_style: cover
social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS
_comments:
  description: It's Timiu here! 
  blurb: A passionate software developer
